# Go parameters
GOCMD=go
GOBUILD=$(GOCMD) build

# Docker parameters
DOCKER=docker
DOCKER_BUILD=$(DOCKER) build
DOCKER_RUN=$(DOCKER) run
DOCKER_RM=$(DOCKER) rm
DOCKER_RUN_COMMON=$(DOCKER_RUN) -d

BASE=github.com/safecorners/les-infideles

BIN=bin/

# Bookings
BOOKINGS=bookings
BOOKINGS_DOCKER_TAG=bookings
BOOKINGS_DOCKER_NAME=bookings
BOOKINGS_BIN=$(BOOKINGS)/$(BIN)/bookings
BOOKINGS_MAIN=$(BOOKINGS)/bookings.go

# Movies
MOVIES=movies
MOVIES_DOCKER_TAG=movies
MOVIES_DOCKER_NAME=movies
MOVIES_BIN=$(MOVIES)/$(BIN)/movies
MOVIES_MAIN=$(MOVIES)/movies.go

# Showtimes
SHOWTIMES=showtimes
SHOWTIMES_DOCKER_TAG=showtimes
SHOWTIMES_DOCKER_NAME=showtimes
SHOWTIMES_BIN=$(SHOWTIMES)/$(BIN)/showtimes
SHOWTIMES_MAIN=$(SHOWTIMES)/showtimes.go

# Users
USERS=users
USERS_DOCKER_TAG=users
USERS_DOCKER_NAME=users
USERS_BIN=$(USERS)/$(BIN)/users
USERS_MAIN=$(USERS)/users.go

all: build docker

build: 
	$(GOBUILD) -o $(BOOKINGS_BIN) $(BOOKINGS_MAIN)
	$(GOBUILD) -o $(MOVIES_BIN) $(MOVIES_MAIN)
	$(GOBUILD) -o $(SHOWTIMES_BIN) $(SHOWTIMES_MAIN)
	$(GOBUILD) -o $(USERS_BIN) $(USERS_MAIN)

docker:
	$(DOCKER_BUILD) -t $(BOOKINGS_TAG) $(BOOKINGS)
	$(DOCKER_BUILD) -t $(MOVIES_TAG) $(MOVIES)
	$(DOCKER_BUILD) -t $(SHOWTIMES_TAG) $(SHOWTIMES)
	$(DOCKER_BUILD) -t $(USERS_TAG) $(USERS)
stop:
	$(DOCKER_RM) -f $(BOOKINGS_DOCKER_NAME)
	$(DOCKER_RM) -f $(MOVIES_DOCKER_NAME)
	$(DOCKER_RM) -f $(SHOWTIMES_DOCKER_NAME)
	$(DOCKER_RM) -f $(USERS_DOCKER_NAME)
run:
	$(DOCKER_RUN_COMMON) --name $(BOOKINGS_DOCKER_NAME) -p 8003:8003 $(BOOKINGS_DOCKER_TAG)
	$(DOCKER_RUN_COMMON) --name $(MOVIES_DOCKER_NAME) -p 8001:8001 $(MOVIES_DOCKER_TAG)
	$(DOCKER_RUN_COMMON) --name $(SHOWTIMES_DOCKER_NAME) -p 8002:8002 $(SHOWTIMES_DOCKER_TAG)
	$(DOCKER_RUN_COMMON) --name $(USERS_DOCKER_NAME) -p 8000:8000 $(USERS_DOCKER_TAG)

